server:
  port: 8096

spring:
  application:
    name: kawaii-admin

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  # 从Nacos配置中心加载配置
  config:
    import:
      - nacos:${spring.application.name}.yaml
      - nacos:kawaii-common.yaml

  # Nacos配置
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:nacos}
      discovery:
        namespace: ${NACOS_NAMESPACE:public}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
      config:
        namespace: ${NACOS_NAMESPACE:public}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        file-extension: yaml

# MyBatis-Plus配置
mybatis-plus:
  # 实体类包路径
  type-aliases-package: com.kawaiichainwallet.admin.entity

