server:
  port: 8080

spring:
  application:
    name: kawaii-gateway

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  # 从Nacos配置中心加载配置
  config:
    import:
      - nacos:${spring.application.name}.yaml
      - nacos:kawaii-common.yaml

  # 明确指定为 Reactive Web 应用
  main:
    web-application-type: reactive

  # Nacos配置
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:nacos}
      discovery:
        namespace: ${NACOS_NAMESPACE:public}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
      config:
        namespace: ${NACOS_NAMESPACE:public}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        file-extension: yaml

    # Gateway基础配置
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true