server:
  port: 8080

spring:
  application:
    name: kawaii-gateway

  # 明确指定为 Reactive Web 应用
  main:
    web-application-type: reactive

  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      database: 1
      timeout: 5000ms

  # Gateway配置
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # 用户服务路由 - 统一规范为 /api/v1/user/**
        - id: kawaii-user
          uri: lb://kawaii-user
          predicates:
            - Path=/api/v1/user/**
          filters:
            - name: Authentication
            - RewritePath=/api/v1/user/(?<segment>.*), /$\{segment}
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter:
                  replenish-rate: 10
                  burst-capacity: 20
                  requested-tokens: 1
          order: 1

        # 钱包核心服务路由 - 统一规范为 /api/v1/core/**
        - id: kawaii-core
          uri: lb://kawaii-core
          predicates:
            - Path=/api/v1/core/**
          filters:
            - name: Authentication
            - RewritePath=/api/v1/core/(?<segment>.*), /$\{segment}
          order: 2

        # 支付服务路由 - 统一规范为 /api/v1/payment/**
        - id: kawaii-payment
          uri: lb://kawaii-payment
          predicates:
            - Path=/api/v1/payment/**
          filters:
            - name: Authentication
            - RewritePath=/api/v1/payment/(?<segment>.*), /$\{segment}
          order: 3

      # 全局过滤器配置
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

      # 全局CORS配置
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

# 日志配置
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      show-details: when_authorized

# 应用安全配置
app:
  jwt:
    secret: kawaii-chain-wallet-secret-key-2025
    access-token-expiration: 900000  # 15分钟
    refresh-token-expiration: 604800000  # 7天
  services:
    user:
      url: http://localhost:8082
    core:
      url: http://localhost:8083
    payment:
      url: http://localhost:8084
  security:
    routes:
      # 公开路径 - 无需认证
      public-paths:
        - "/api/v1/user/register/**"
        - "/api/v1/user/health"
        - "/api/v1/user/login"
        - "/api/v1/user/login/otp"
        - "/api/v1/user/send-login-otp"
        - "/api/v1/user/refresh"
        - "/api/v1/user/check-**"
        - "/actuator/health"
        - "/swagger-ui/**"
        - "/v3/api-docs/**"

      # 受保护路径 - 需要认证
      protected-paths:
        - "/api/v1/user/profile/**"
        - "/api/v1/user/logout"
        - "/api/v1/user/validate"
        - "/api/v1/core/**"
        - "/api/v1/payment/**"

      # 角色路径映射 - 需要特定角色
      role-paths:
        "/api/v1/user/admin/**": ["ADMIN"]
        "/api/v1/user/users": ["ADMIN"]  # 获取用户列表
        "/api/v1/core/admin/**": ["ADMIN", "WALLET_ADMIN"]
        "/api/v1/payment/merchant/**": ["MERCHANT"]

      # 管理员路径 - 仅管理员可访问
      admin-paths:
        - "/actuator/**"
        - "/api/v1/admin/**"

      # 内部路径 - 仅服务间调用
      internal-paths:
        - "/internal/**"