spring:
  # 数据库配置 - 本地PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/kawaii_user_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC

# 应用业务配置 - 本地开发
app:
  # 认证配置
  auth:
    max-login-attempts: 10  # 本地开发放宽限制
    account-lock-duration: 5  # 5分钟

  # OTP配置
  otp:
    length: 6
    expiration: 600  # 本地开发延长到10分钟
    rate-limit: 30   # 30秒内只能发送1次
    max-attempts: 10  # 本地开发放宽限制

  # 短信服务配置 (本地开发使用测试配置)
  sms:
    provider: mock  # 本地使用模拟短信
    access-key-id: test-access-key
    access-key-secret: test-secret
    sign-name: KawaiiWallet
    template-code: SMS_TEST

  # 邮件服务配置 (本地开发)
  email:
    host: localhost
    port: 1025  # MailHog端口
    username: test
    password: test
    from: noreply@localhost

  # 微服务地址配置 (本地环境)
  services:
    user:
      url: http://localhost:8082
    core:
      url: http://localhost:8083
    payment:
      url: http://localhost:8084

  # 安全配置
  security:
    # JWT配置
    jwt:
      # EC私钥 (ES256算法，PKCS#8格式) - P-256曲线
      # 仅user服务需要私钥用于生成Token
      private-key: |
        -----BEGIN PRIVATE KEY-----
        MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgQlwptdFKqSYDlfrm
        Ho42sEgGxgPyHdONydLWP1rlYuqhRANCAARBBsoZJYCrhZrqNbfl+H76yOBsU+Gd
        BTFoPykC5WJqasDEG4lx0XIz0jjRbZjRGnr0BiOiUulfODDP6iKAqz6c
        -----END PRIVATE KEY-----

    # CORS配置 - 本地开发允许所有来源
    cors:
      allowed-origins:
        - "http://localhost:3000"
        - "http://localhost:8080"
        - "http://127.0.0.1:3000"
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowed-headers: "*"
      allow-credentials: true

  # 业务配置
  business:
    # 钱包配置
    wallet:
      default-currency: ETH
      min-transfer-amount: 0.0001  # 本地测试使用小金额
      max-transfer-amount: 100

    # 支付配置
    payment:
      timeout: 600  # 本地开发延长超时时间
      retry-times: 5