# ===========================================
# KawaiiChain Wallet 本地开发环境公共配置
# 命名空间: kawaii-local
# 文件名: kawaii-common.yml
# ===========================================

spring:
  # 数据库配置 - 本地PostgreSQL
  datasource:
    driver-class-name: org.postgresql.Driver
    username: rw
    password: Admin!123
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      validation-timeout: 3000
      leak-detection-threshold: 60000

  # Redis配置 - 本地Redis
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      database: 0
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 200
          max-wait: -1ms
          max-idle: 10
          min-idle: 0

  # Jackson统一配置 - 所有微服务共享
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    time-zone: UTC

# Feign配置 - 本地开发
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: full  # 本地开发使用详细日志
  hystrix:
    enabled: false
  okhttp:
    enabled: true


# 管理端点配置 - 本地开发暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# ===========================================
# 应用公共配置
# ===========================================
app:
  # 时区配置
  timezone:
    default: UTC                          # 应用默认时区
    jvm-timezone: UTC                     # JVM时区设置

  # 安全配置
  security:
    # JWT统一配置 - 所有微服务共享
    jwt:
      secret: kawaii-chain-wallet-local-secret-key-2025
      access-token-expiration: 3600      # 1小时 (本地开发)
      refresh-token-expiration: 604800   # 7天
      issuer: kawaii-wallet
      algorithm: HS256                   # 使用HMAC SHA256算法
