spring:
  data:
    # Redis配置 - 用于限流
    redis:
      host: localhost
      port: 6379
      database: 0
      password:
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

  # Gateway通用配置
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # 用户服务路由 - 统一规范为 /api/v1/user/**
            - id: kawaii-user
              uri: lb://kawaii-user
              predicates:
                - Path=/api/v1/user/**
              filters:
                - name: Authentication
                - RewritePath=/api/v1/user/(?<segment>.*), /user/$\{segment}
                - name: RequestRateLimiter
                  args:
                    key-resolver: "#{@ipKeyResolver}"
                    redis-rate-limiter:
                      replenish-rate: 10
                      burst-capacity: 20
                      requested-tokens: 1
              order: 1

            # 钱包核心服务路由 - 统一规范为 /api/v1/core/**
            - id: kawaii-core
              uri: lb://kawaii-core
              predicates:
                - Path=/api/v1/core/**
              filters:
                - name: Authentication
                - RewritePath=/api/v1/core/(?<segment>.*), /core/$\{segment}
              order: 2

            # 支付服务路由 - 统一规范为 /api/v1/payment/**
            - id: kawaii-payment
              uri: lb://kawaii-payment
              predicates:
                - Path=/api/v1/payment/**
              filters:
                - name: Authentication
                - RewritePath=/api/v1/payment/(?<segment>.*), /payment/$\{segment}
              order: 3
          # 全局CORS配置
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOriginPatterns: "*"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
                allowCredentials: true

      # 全局过滤器配置
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

# 应用配置
app:
  # 路由安全配置
  security:
    routes:
      # 公开路径 - 无需认证
      public-paths:
        - "/api/v1/user/auth/**"        # 所有用户认证相关接口
        - "/api/v1/user/check-**"       # 用户检查接口（用户名、邮箱、手机号存在性检查）
        - "/api/v1/core/health"         # 健康检查
        - "/api/v1/payment/webhook/**"  # 支付回调
        - "/actuator/**"
        - "/health"

      # 管理员路径 - 仅管理员可访问
      admin-paths:
        - "/api/v1/user/users"
        - "/api/v1/*/admin/**"

      # 内部路径 - 仅服务间调用
      internal-paths:
        - "/api/v1/*/internal/**"

      # 角色路径映射
      role-paths:
        "/api/v1/payment/admin/**": [ "ADMIN", "PAYMENT_ADMIN" ]
        "/api/v1/core/admin/**": [ "ADMIN", "CORE_ADMIN" ]