spring:
  data:
    # Redis配置 - 用于限流
    redis:
      host: localhost
      port: 6379
      database: 0
      password:
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

  # Gateway通用配置
  cloud:
    gateway:
      server:
        webflux:
          # 全局过滤器配置 - 应用到所有路由
          default-filters:
            - name: Authentication
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

          # 全局CORS配置
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOriginPatterns: "*"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
                allowCredentials: true

          # 路由配置
          routes:
            - id: kawaii-user-route
              uri: lb://kawaii-user
              predicates:
                - Path=/kawaii-user/**
              filters:
                - StripPrefix=1
            - id: kawaii-core-route
              uri: lb://kawaii-core
              predicates:
                - Path=/kawaii-core/**
              filters:
                - StripPrefix=1
            - id: kawaii-payment-route
              uri: lb://kawaii-payment
              predicates:
                - Path=/kawaii-payment/**
              filters:
                - StripPrefix=1
            - id: kawaii-merchant-route
              uri: lb://kawaii-merchant
              predicates:
                - Path=/kawaii-merchant/**
              filters:
                - StripPrefix=1
            - id: kawaii-notification-route
              uri: lb://kawaii-notification
              predicates:
                - Path=/kawaii-notification/**
              filters:
                - StripPrefix=1

# 应用配置
app:
  # 路由安全配置
  security:
    # JWT配置 - 使用与user服务相同的EC公钥验证Token
    jwt:
      # EC公钥 (ES256算法) - P-256曲线
      public-key: |
        -----BEGIN PUBLIC KEY-----
        MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEQQbKGSWAq4Wa6jW35fh++sjgbFPh
        nQUxaD8pAuViamrAxBuJcdFyM9I40W2Y0Rp69AYjolLpXzgwz+oigKs+nA==
        -----END PUBLIC KEY-----
    routes:
      # 公开路径 - 无需认证
      public-paths:
        - "/kawaii-user/auth/login"           # 登录接口
        - "/kawaii-user/auth/login-with-otp"  # OTP登录接口
        - "/kawaii-user/auth/register"        # 注册接口
        - "/kawaii-user/auth/send-*-otp"      # 发送OTP接口
        - "/kawaii-user/auth/refresh"         # 刷新Token接口
        - "/kawaii-user/check-**"             # 用户检查接口
        - "/kawaii-core/health"               # 健康检查
        - "/kawaii-payment/webhook/**"        # 支付回调
        - "/actuator/**"                      # 监控端点
        - "/health"                           # 健康检查

      # 可选认证路径 - Token无效也允许访问
      optional-auth-paths:
        - "/kawaii-user/auth/logout"          # 登出接口

      # 内部路径 - 仅服务间调用，阻止外部直接访问
      internal-paths:
        - "/kawaii-*/internal/**"

# Gateway请求日志配置
gateway:
  request-logging:
    # 是否启用请求日志
    enabled: true

    # 是否记录请求头（本地开发启用，生产环境可关闭）
    log-headers: true

    # 是否记录请求体（本地开发可启用，生产环境建议关闭）
    log-request-body: true

    # 是否记录响应体（本地开发可启用，生产环境建议关闭）
    log-response-body: true

    # 记录响应体的最大大小（字节）
    max-response-body-size: 2048

    # 是否记录敏感路径的详细信息（建议关闭）
    log-sensitive-paths: false

    # 排除的路径模式（不记录日志）
    exclude-paths:
      - "/actuator/**"
      - "/health"
      - "/favicon.ico"
      - "/kawaii-*/actuator/**"

    # 需要脱敏的字段名
    sensitive-fields:
      - "password"
      - "token"
      - "authorization"
      - "cookie"
      - "session"
      - "secret"
      - "key"
      - "passwd"
      - "pwd"
      - "credential"
      - "refreshToken"
      - "accessToken"
      - "otp"
      - "otpCode"
      - "verificationCode"

    # 敏感路径模式（这些路径的详细信息会被脱敏处理）
    sensitive-paths:
      - "/kawaii-user/auth/login"
      - "/kawaii-user/auth/register"
      - "/kawaii-user/auth/refresh"
      - "/kawaii-user/auth/send-**-otp"
      - "/kawaii-admin/auth/**"
      - "/kawaii-*/password/**"