spring:
  # 数据库配置 - 本地PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/kawaii_admin_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC

  # Redis配置
  data:
    redis:
      database: 2  # 使用独立的database，与其他服务隔离（user=1, gateway=0）
      # host、port、password 继承自 kawaii-common.yaml

  # Cloud配置
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000   # 连接超时5秒
            readTimeout: 10000     # 读取超时10秒
            loggerLevel: basic     # 日志级别：NONE, BASIC, HEADERS, FULL
      # 启用okhttp客户端（性能更好）
      okhttp:
        enabled: true
      # 启用压缩
      compression:
        request:
          enabled: true
          min-request-size: 2048
        response:
          enabled: true

# 应用业务配置 - 本地开发
app:
  # 管理员认证配置
  admin:
    # 登录安全配置
    login:
      max-attempts: 5  # 管理员登录失败次数限制
      lock-duration: 15  # 15分钟锁定
      session-timeout: 1800  # 30分钟会话超时

    # 权限配置
    permissions:
      super-admin-roles: ["SUPER_ADMIN"]  # 超级管理员角色
      read-only-roles: ["READ_ONLY"]      # 只读角色

    # 审计配置
    audit:
      enable: true
      sensitive-operations:  # 需要记录的敏感操作
        - "CREATE_ADMIN"
        - "DELETE_ADMIN"
        - "ASSIGN_ROLE"
        - "UPDATE_CONFIG"
        - "EXPORT_DATA"
      retention-days: 90  # 审计日志保留90天

  # 系统配置管理
  system:
    config:
      # 配置变更审批
      require-approval: false  # 本地开发关闭审批
      auto-backup: true        # 自动备份配置

    # 数据导出配置
    export:
      max-records: 10000       # 单次导出最大记录数
      formats: ["CSV", "EXCEL", "JSON"]
      temp-dir: "/tmp/kawaii-admin-exports"


  # 安全配置
  security:
    # JWT配置 - 管理员系统使用独立的密钥对
    jwt:
      # EC私钥 (ES256算法，PKCS#8格式) - P-256曲线
      # 管理员服务需要私钥用于生成Admin Token
      # 注意：与用户系统使用不同的密钥对，提高安全性
      private-key: |
        -----BEGIN PRIVATE KEY-----
        MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgVX8mK2pLdN7JhY3w
        5FqR8tPzGxYnH9WJLmKvU4DfE6qhRANCAATZxPwH5K8nYzQvLmF3J9dR2hT8UqWe
        7vNcX1mF9YpK2JhLrT8VwXqE4nH7DyU9Gf3mZk1RtYwPxLqK8vH2J4nT
        -----END PRIVATE KEY-----

    # CORS配置 - 本地开发允许管理后台来源
    cors:
      allowed-origins:
        - "http://localhost:3001"    # 管理后台前端
        - "http://localhost:8080"    # Gateway
        - "http://127.0.0.1:3001"
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowed-headers: "*"
      allow-credentials: true

  # 文件上传配置
  upload:
    max-file-size: 10MB      # 最大文件大小
    allowed-types: ["jpg", "png", "pdf", "csv", "xlsx"]
    upload-path: "/tmp/kawaii-admin-uploads"