server:
  port: 8091
  servlet:
    context-path: /${spring.application.name}

spring:
  application:
    name: kawaii-user

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  # 从Nacos配置中心加载配置
  config:
    import:
      - nacos:${spring.application.name}.yaml
      - nacos:kawaii-common.yaml

  # Nacos配置
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:nacos}
      discovery:
        namespace: ${NACOS_NAMESPACE:public}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
      config:
        namespace: ${NACOS_NAMESPACE:public}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        file-extension: yaml


# MyBatis-Plus通用配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  type-aliases-package: com.kawaiichainwallet.user.entity

# Leaf分布式ID生成器配置
leaf:
  segment:
    enable: true
    jdbc:
      # 使用当前数据源配置，在Nacos中会覆盖
      url: ${spring.datasource.url:jdbc:postgresql://localhost:5433/kawaii_user_db}
      username: ${spring.datasource.username:kawaii_user}
      password: ${spring.datasource.password:password}
      driver: ${spring.datasource.driver-class-name:org.postgresql.Driver}
  snowflake:
    enable: true
    port: ${server.port:8091}
    use-nacos: true
    # Nacos服务发现地址，用于分布式协调
    zk-address: ${spring.cloud.nacos.discovery.server-addr:localhost:8848}